const cv=document.querySelector('#tetris'),x=cv.getContext('2d'),scoreEl=document.querySelector('#score'),msg=document.querySelector('#tmsg'),players=document.querySelector('#players');x.scale(30,30);const S=['#00d6d6','#4f7cff','#ff9d2e','#ffda3d','#52c96d','#b05cff','#f45b69'],P=[[[1,1,1,1]],[[2,0,0],[2,2,2]],[[0,0,3],[3,3,3]],[[4,4],[4,4]],[[0,5,5],[5,5,0]],[[0,6,0],[6,6,6]],[[7,7,0],[0,7,7]]];let a=Array.from({length:20},()=>Array(10).fill(0)),p,score=0,peer,conns=[],pending=0,last=0,dead=false;
function piece(){let m=P[Math.floor(Math.random()*P.length)].map(r=>r.slice());return{m,x:3,y:0}}
function hit(m,o){for(let y=0;y<m.length;y++)for(let z=0;z<m[y].length;z++)if(m[y][z]&&(a[y+o.y]&&a[y+o.y][z+o.x])!==0)return true;return false}
function merge(){p.m.forEach((r,y)=>r.forEach((v,z)=>{if(v)a[y+p.y][z+p.x]=v}));let n=0;a=a.filter(r=>{if(r.every(Boolean)){n++;return false}return true});while(a.length<20)a.unshift(Array(10).fill(0));if(n){score+=n*n*100;scoreEl.textContent=score;if(n>1)send({t:'attack',n:n-1}),msg.textContent=`${n-1}줄 공격 전송!`}}
function draw(){x.fillStyle='#14213d';x.fillRect(0,0,10,20);[a,p?.m].forEach((m,k)=>{if(!m)return;m.forEach((r,y)=>r.forEach((v,z)=>{if(v){x.fillStyle=S[v-1];x.fillRect(z+(k?p.x:0),y+(k?p.y:0),.94,.94)}}))})}
function fall(){p.y++;if(hit(p.m,p)){p.y--;merge();p=piece();if(hit(p.m,p)){dead=true;msg.textContent='게임 오버! 새로고침해 다시 시작하세요.'}}}
function rotate(){let m=p.m[0].map((_,i)=>p.m.map(r=>r[i]).reverse());if(!hit(m,p))p.m=m}function move(n){p.x+=n;if(hit(p.m,p))p.x-=n}function drop(){while(!hit(p.m,{...p,y:p.y+1}))p.y++;fall()}
function loop(t){if(!dead&&t-last>700){fall();last=t}draw();requestAnimationFrame(loop)}
function send(d){conns.forEach(c=>c.open&&c.send(d))}function connect(c){conns.push(c);players.textContent=`${conns.length+1}/4`;c.on('data',d=>{if(d.t==='attack'){for(let i=0;i<d.n;i++){a.shift();let r=Array(10).fill(8);r[Math.floor(Math.random()*10)]=0;a.push(r)}msg.textContent='방해 줄이 왔어요!' }});c.on('close',()=>{conns=conns.filter(q=>q!==c);players.textContent=`${conns.length+1}/4`})}
function host(){let id='tetris-'+document.querySelector('#room').value.trim().toLowerCase();if(id==='tetris-'){id='tetris-'+Math.random().toString(36).slice(2,8)}document.querySelector('#room').value=id.slice(8).toUpperCase();peer=new Peer(id);peer.on('open',()=>msg.textContent='방 생성 완료! 코드를 친구에게 공유하세요.');peer.on('connection',c=>{if(conns.length<3)connect(c)});peer.on('error',e=>msg.textContent='방 생성 오류: 다른 코드를 사용하세요.')}function join(){let code=document.querySelector('#room').value.trim().toLowerCase();if(!code)return msg.textContent='방 코드를 입력하세요.';peer=new Peer();peer.on('open',()=>{let c=peer.connect('tetris-'+code);c.on('open',()=>{connect(c);msg.textContent='배틀 방에 참가했습니다!'})});peer.on('error',()=>msg.textContent='방에 연결할 수 없어요. 코드를 확인하세요.')}
document.querySelector('#host').onclick=host;document.querySelector('#join').onclick=join;addEventListener('keydown',e=>{let k=e.key;if(['ArrowLeft','ArrowRight','ArrowDown','ArrowUp',' '].includes(k))e.preventDefault();if(k==='ArrowLeft')move(-1);if(k==='ArrowRight')move(1);if(k==='ArrowDown')fall();if(k==='ArrowUp')rotate();if(k===' ')drop()});document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>({left:()=>move(-1),right:()=>move(1),down:fall,rotate,drop}[b.dataset.key]()));p=piece();requestAnimationFrame(loop);
